spring.datasource.url=jdbc:MySQL://localhost:3306/employee_db
spring.datasource.username=jpauser
spring.datasource.password=jpapwd

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update

server.port=8081
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
